// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm-9UeVLvyYfgUuCyOctcaok8V_CpUzD0',
    appId: '1:315622785421:web:63f9a7df43e4904216fdc4',
    messagingSenderId: '315622785421',
    projectId: 'device-streaming-bfb6b880',
    authDomain: 'device-streaming-bfb6b880.firebaseapp.com',
    storageBucket: 'device-streaming-bfb6b880.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJuHBn5v_5LypAoQzNKXUAF08Lf-INo1c',
    appId: '1:315622785421:android:ac49089279fe7f5516fdc4',
    messagingSenderId: '315622785421',
    projectId: 'device-streaming-bfb6b880',
    storageBucket: 'device-streaming-bfb6b880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMW6gRHVifSEYhQvLxPlsErWsvQvQrpo',
    appId: '1:315622785421:ios:35363ae82efaaced16fdc4',
    messagingSenderId: '315622785421',
    projectId: 'device-streaming-bfb6b880',
    storageBucket: 'device-streaming-bfb6b880.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMW6gRHVifSEYhQvLxPlsErWsvQvQrpo',
    appId: '1:315622785421:ios:35363ae82efaaced16fdc4',
    messagingSenderId: '315622785421',
    projectId: 'device-streaming-bfb6b880',
    storageBucket: 'device-streaming-bfb6b880.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm-9UeVLvyYfgUuCyOctcaok8V_CpUzD0',
    appId: '1:315622785421:web:a509f3e7c5711c8216fdc4',
    messagingSenderId: '315622785421',
    projectId: 'device-streaming-bfb6b880',
    authDomain: 'device-streaming-bfb6b880.firebaseapp.com',
    storageBucket: 'device-streaming-bfb6b880.firebasestorage.app',
  );
}
